ALTER TABLE history ADD COLUMN is_intercepted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE history ADD COLUMN is_rewritten INTEGER NOT NULL DEFAULT 0;
ALTER TABLE history ADD COLUMN is_failed INTEGER NOT NULL DEFAULT 0;
